/*
 * This file is generated by jOOQ.
 */
package Pharmacy.dbo.tables.daos;


import Pharmacy.dbo.tables.Pharmacymedicine;
import Pharmacy.dbo.tables.records.PharmacymedicineRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PharmacymedicineDao extends DAOImpl<PharmacymedicineRecord, Pharmacy.dbo.tables.pojos.Pharmacymedicine, Object> {

    /**
     * Create a new PharmacymedicineDao without any configuration
     */
    public PharmacymedicineDao() {
        super(Pharmacymedicine.PHARMACYMEDICINE, Pharmacy.dbo.tables.pojos.Pharmacymedicine.class);
    }

    /**
     * Create a new PharmacymedicineDao with an attached configuration
     */
    @Autowired
    public PharmacymedicineDao(Configuration configuration) {
        super(Pharmacymedicine.PHARMACYMEDICINE, Pharmacy.dbo.tables.pojos.Pharmacymedicine.class, configuration);
    }

    @Override
    public Object getId(Pharmacy.dbo.tables.pojos.Pharmacymedicine object) {
        return object.getPmid();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchRangeOfPmid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Pharmacymedicine.PHARMACYMEDICINE.PMID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchByPmid(Object... values) {
        return fetch(Pharmacymedicine.PHARMACYMEDICINE.PMID, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Pharmacy.dbo.tables.pojos.Pharmacymedicine fetchOneByPmid(Object value) {
        return fetchOne(Pharmacymedicine.PHARMACYMEDICINE.PMID, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchRangeOfInstock(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Pharmacymedicine.PHARMACYMEDICINE.INSTOCK, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchByInstock(Object... values) {
        return fetch(Pharmacymedicine.PHARMACYMEDICINE.INSTOCK, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchRangeOfMedicineid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Pharmacymedicine.PHARMACYMEDICINE.MEDICINEID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchByMedicineid(Object... values) {
        return fetch(Pharmacymedicine.PHARMACYMEDICINE.MEDICINEID, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchRangeOfPharmacyid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Pharmacymedicine.PHARMACYMEDICINE.PHARMACYID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Pharmacymedicine> fetchByPharmacyid(Object... values) {
        return fetch(Pharmacymedicine.PHARMACYMEDICINE.PHARMACYID, values);
    }
}
