/*
 * This file is generated by jOOQ.
 */
package Pharmacy.dbo.tables.daos;


import Pharmacy.dbo.tables.Roles;
import Pharmacy.dbo.tables.records.RolesRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RolesDao extends DAOImpl<RolesRecord, Pharmacy.dbo.tables.pojos.Roles, Object> {

    /**
     * Create a new RolesDao without any configuration
     */
    public RolesDao() {
        super(Roles.ROLES, Pharmacy.dbo.tables.pojos.Roles.class);
    }

    /**
     * Create a new RolesDao with an attached configuration
     */
    @Autowired
    public RolesDao(Configuration configuration) {
        super(Roles.ROLES, Pharmacy.dbo.tables.pojos.Roles.class, configuration);
    }

    @Override
    public Object getId(Pharmacy.dbo.tables.pojos.Roles object) {
        return object.getRoleid();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Roles> fetchRangeOfRoleid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Roles.ROLES.ROLEID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<Pharmacy.dbo.tables.pojos.Roles> fetchByRoleid(Object... values) {
        return fetch(Roles.ROLES.ROLEID, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Pharmacy.dbo.tables.pojos.Roles fetchOneByRoleid(Object value) {
        return fetchOne(Roles.ROLES.ROLEID, value);
    }

    /**
     * Fetch records that have <code>roleType BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<Pharmacy.dbo.tables.pojos.Roles> fetchRangeOfRoletype(String lowerInclusive, String upperInclusive) {
        return fetchRange(Roles.ROLES.ROLETYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>roleType IN (values)</code>
     */
    public List<Pharmacy.dbo.tables.pojos.Roles> fetchByRoletype(String... values) {
        return fetch(Roles.ROLES.ROLETYPE, values);
    }
}
