/*
 * This file is generated by jOOQ.
 */
package PharmacyDataAccess;


import PharmacyDataAccess.tables.Employee;
import PharmacyDataAccess.tables.Medicine;
import PharmacyDataAccess.tables.Pharmacy;
import PharmacyDataAccess.tables.Pharmacymedicine;
import PharmacyDataAccess.tables.Roles;
import PharmacyDataAccess.tables.Salary;
import PharmacyDataAccess.tables.Transactions;
import PharmacyDataAccess.tables.Users;
import PharmacyDataAccess.tables.records.EmployeeRecord;
import PharmacyDataAccess.tables.records.MedicineRecord;
import PharmacyDataAccess.tables.records.PharmacyRecord;
import PharmacyDataAccess.tables.records.PharmacymedicineRecord;
import PharmacyDataAccess.tables.records.RolesRecord;
import PharmacyDataAccess.tables.records.SalaryRecord;
import PharmacyDataAccess.tables.records.TransactionsRecord;
import PharmacyDataAccess.tables.records.UsersRecord;

import javax.annotation.processing.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>dbo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployeeRecord> PK_EMPLOYEE = UniqueKeys0.PK_EMPLOYEE;
    public static final UniqueKey<MedicineRecord> PK_MEDICINE = UniqueKeys0.PK_MEDICINE;
    public static final UniqueKey<PharmacyRecord> PK_PHARMACY = UniqueKeys0.PK_PHARMACY;
    public static final UniqueKey<PharmacymedicineRecord> PK_PHARMACYMEDICINE = UniqueKeys0.PK_PHARMACYMEDICINE;
    public static final UniqueKey<RolesRecord> PK_ROLES = UniqueKeys0.PK_ROLES;
    public static final UniqueKey<SalaryRecord> PK_SALARY = UniqueKeys0.PK_SALARY;
    public static final UniqueKey<TransactionsRecord> PK_TRANSACTIONS = UniqueKeys0.PK_TRANSACTIONS;
    public static final UniqueKey<UsersRecord> PK_USERS = UniqueKeys0.PK_USERS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<EmployeeRecord> PK_EMPLOYEE = Internal.createUniqueKey(Employee.EMPLOYEE, "PK_Employee", Employee.EMPLOYEE.EMPLOYEEID);
        public static final UniqueKey<MedicineRecord> PK_MEDICINE = Internal.createUniqueKey(Medicine.MEDICINE, "PK_Medicine", Medicine.MEDICINE.MEDICINEID);
        public static final UniqueKey<PharmacyRecord> PK_PHARMACY = Internal.createUniqueKey(Pharmacy.PHARMACY, "PK_Pharmacy", Pharmacy.PHARMACY.PHARMACYID);
        public static final UniqueKey<PharmacymedicineRecord> PK_PHARMACYMEDICINE = Internal.createUniqueKey(Pharmacymedicine.PHARMACYMEDICINE, "PK_PharmacyMedicine", Pharmacymedicine.PHARMACYMEDICINE.PMID);
        public static final UniqueKey<RolesRecord> PK_ROLES = Internal.createUniqueKey(Roles.ROLES, "PK_Roles", Roles.ROLES.ROLEID);
        public static final UniqueKey<SalaryRecord> PK_SALARY = Internal.createUniqueKey(Salary.SALARY, "PK_Salary", Salary.SALARY.SALARYID);
        public static final UniqueKey<TransactionsRecord> PK_TRANSACTIONS = Internal.createUniqueKey(Transactions.TRANSACTIONS, "PK_Transactions", Transactions.TRANSACTIONS.TRANSACTIONID);
        public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, "PK_Users", Users.USERS.USERID);
    }
}
