/*
 * This file is generated by jOOQ.
 */
package PharmacyDataAccess;


import PharmacyDataAccess.tables.Medicine;
import PharmacyDataAccess.tables.Pharmacy;
import PharmacyDataAccess.tables.Pharmacymedicine;
import PharmacyDataAccess.tables.Roles;
import PharmacyDataAccess.tables.Salary;
import PharmacyDataAccess.tables.Transactions;
import PharmacyDataAccess.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in dbo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dbo.Medicine</code>.
     */
    public static final Medicine MEDICINE = Medicine.MEDICINE;

    /**
     * The table <code>dbo.Pharmacy</code>.
     */
    public static final Pharmacy PHARMACY = Pharmacy.PHARMACY;

    /**
     * The table <code>dbo.PharmacyMedicine</code>.
     */
    public static final Pharmacymedicine PHARMACYMEDICINE = Pharmacymedicine.PHARMACYMEDICINE;

    /**
     * The table <code>dbo.Roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>dbo.Salary</code>.
     */
    public static final Salary SALARY = Salary.SALARY;

    /**
     * The table <code>dbo.Transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>dbo.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
