/*
 * This file is generated by jOOQ.
 */
package PharmacyDataAccess.tables.daos;


import PharmacyDataAccess.tables.Users;
import PharmacyDataAccess.tables.records.UsersRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UsersDao extends DAOImpl<UsersRecord, PharmacyDataAccess.tables.pojos.Users, Object> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, PharmacyDataAccess.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    @Autowired
    public UsersDao(Configuration configuration) {
        super(Users.USERS, PharmacyDataAccess.tables.pojos.Users.class, configuration);
    }

    @Override
    public Object getId(PharmacyDataAccess.tables.pojos.Users object) {
        return object.getUserid();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfUserid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Users.USERS.USERID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByUserid(Object... values) {
        return fetch(Users.USERS.USERID, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public PharmacyDataAccess.tables.pojos.Users fetchOneByUserid(Object value) {
        return fetchOne(Users.USERS.USERID, value);
    }

    /**
     * Fetch records that have <code>city BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfCity(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.CITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByCity(String... values) {
        return fetch(Users.USERS.CITY, values);
    }

    /**
     * Fetch records that have <code>firstName BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfFirstname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.FIRSTNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>firstName IN (values)</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByFirstname(String... values) {
        return fetch(Users.USERS.FIRSTNAME, values);
    }

    /**
     * Fetch records that have <code>lastName BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfLastname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.LASTNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lastName IN (values)</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByLastname(String... values) {
        return fetch(Users.USERS.LASTNAME, values);
    }

    /**
     * Fetch records that have <code>state BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfState(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByState(String... values) {
        return fetch(Users.USERS.STATE, values);
    }

    /**
     * Fetch records that have <code>userAddress BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfUseraddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.USERADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>userAddress IN (values)</code>
     */
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByUseraddress(String... values) {
        return fetch(Users.USERS.USERADDRESS, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfZip(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Users.USERS.ZIP, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByZip(Object... values) {
        return fetch(Users.USERS.ZIP, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchRangeOfRoleid(Object lowerInclusive, Object upperInclusive) {
        return fetchRange(Users.USERS.ROLEID, lowerInclusive, upperInclusive);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<PharmacyDataAccess.tables.pojos.Users> fetchByRoleid(Object... values) {
        return fetch(Users.USERS.ROLEID, values);
    }
}
