/*
 * This file is generated by jOOQ.
 */
package Pharmacy.dbo.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Medicine", schema = "dbo", uniqueConstraints = {
    @UniqueConstraint(name = "PK_Medicine", columnNames = {"medicineId"})
})
public interface IMedicine extends Serializable {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setMedicineid(Object value);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Id
    @Column(name = "medicineId")
    public Object getMedicineid();

    /**
     * Setter for <code>dbo.Medicine.cost</code>.
     */
    public void setCost(BigDecimal value);

    /**
     * Getter for <code>dbo.Medicine.cost</code>.
     */
    @Column(name = "cost", precision = 10, scale = 2)
    public BigDecimal getCost();

    /**
     * Setter for <code>dbo.Medicine.medicineName</code>.
     */
    public void setMedicinename(String value);

    /**
     * Getter for <code>dbo.Medicine.medicineName</code>.
     */
    @Column(name = "medicineName", length = 50)
    public String getMedicinename();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IMedicine
     */
    public void from(Pharmacy.dbo.tables.interfaces.IMedicine from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IMedicine
     */
    public <E extends Pharmacy.dbo.tables.interfaces.IMedicine> E into(E into);
}
