/*
 * This file is generated by jOOQ.
 */
package Pharmacy.dbo.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Pharmacy", schema = "dbo", uniqueConstraints = {
    @UniqueConstraint(name = "PK_Pharmacy", columnNames = {"pharmacyId"})
})
public interface IPharmacy extends Serializable {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setPharmacyid(Object value);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Id
    @Column(name = "pharmacyId")
    public Object getPharmacyid();

    /**
     * Setter for <code>dbo.Pharmacy.city</code>.
     */
    public void setCity(String value);

    /**
     * Getter for <code>dbo.Pharmacy.city</code>.
     */
    @Column(name = "city", length = 50)
    public String getCity();

    /**
     * Setter for <code>dbo.Pharmacy.pharmacyAddress</code>.
     */
    public void setPharmacyaddress(String value);

    /**
     * Getter for <code>dbo.Pharmacy.pharmacyAddress</code>.
     */
    @Column(name = "pharmacyAddress", length = 50)
    public String getPharmacyaddress();

    /**
     * Setter for <code>dbo.Pharmacy.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>dbo.Pharmacy.state</code>.
     */
    @Column(name = "state", length = 30)
    public String getState();

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setZip(Object value);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Column(name = "zip")
    public Object getZip();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPharmacy
     */
    public void from(Pharmacy.dbo.tables.interfaces.IPharmacy from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPharmacy
     */
    public <E extends Pharmacy.dbo.tables.interfaces.IPharmacy> E into(E into);
}
